### ISSUE TITLE
`not a git repository (or any of the parent directories): .git`

### ISSUE THREAD

**Issue by multimeric** [PDB-REDO/cif-tools#1]
I initially tried to `git clone` this repo, but then realised that I would have to run `cmake` if I did that, so I instead downloaded the source bundle from the releases page, and followed the instructions. However once I got to the make stage, it threw this error:
```bash
$ make
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
mkdir -p obj
>> src/pdb2cif.cpp
rm -f version-info-*.txt
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by mhekkel** [comment]
download or git, no matter what you choose, you still have to use cmake.
