### ISSUE TITLE
error: no template named 'stack' in namespace 'std'

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/cif-tools#2]
```
/disk-samsung/freebsd-ports/science/cif-tools/work/cif-tools-1.0.3/src/mmCQL.cpp:468:7: error: no template named 'stack' in namespace 'std'
        std::stack<unicode> mBuffer;
        ~~~~~^
1 error generated.
```

Did you forget to include ```<stack>``` in mmCQL.cpp?

clang-14
FreeBSD 13.1

**Comment by mhekkel** [comment]
No, I did not forget it, it was simply not needed in all other compiler/OS combo's I tried. But I'll add it.

**Comment by yurivict** [comment]
All used STL templates require corresponding include lines.
