### ISSUE TITLE
libconfig::libconfig isn't found

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/cif-tools#4]
```
CMake Error at CMakeLists.txt:128 (target_link_libraries):
  Target "pdb2cif" links to:

    libconfig::libconfig

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

[libconfig](https://github.com/hyperrealm/libconfig) doesn't install cmake files.
It can't be found with ```find_package(libconfig QUIET)```, like you attempt to do it.

Version: 1.0.5
clang-14
FreeBSD 13.1

**Comment by mhekkel** [comment]
You are chasing me ;-)

I'm in the progress of updating all my code to get it ready to be included in Debian. And e.g. libconfig was an attempt to ditch boost::program_options and thus a runtime dependency. However, there are already dozens of libconfig's around and so I ended up with the name libcfp.

So please be patient, within a week or two I hope all the tools built upon libcifpp are properly ported and cleaned up.

**Comment by yurivict** [comment]
Ok, thank you.

**Comment by yurivict** [comment]
@mhekkel  You use ```libcfp``` which was last updated in 2014.
Are you sure that there are no better options to parse formulas?
What about OpenBabel or libavogadro?

**Comment by mhekkel** [comment]
That's very unfortunate, I was referring to https://github.com/mhekkel/libcfp.git but apparently I didn't check good enough and now I have a name clash.

**Comment by mhekkel** [comment]
@yurivict When I create a tar ball containing a .gitmodules file, will the packaging system at FreeBSD pick up the git submodules automatically? That would allow me to add my personal libcfp as submodule without the need to package it separately.

**Comment by yurivict** [comment]
@mhekkel Git submodules are filled up manually by maintainers, they aren't automatic. But yes, many ports import project git submodules for parts that aren't individually ported.

**Comment by yurivict** [comment]
This is not a problem any more.
