### ISSUE TITLE
Error reading the mmcif_pdbx.dic file

### ISSUE THREAD

**Issue by locitran** [PDB-REDO/cif-tools#5]
Hi cif-tools developers,

I am failed to import the dictionary file to pdb2cif as following command:
```
/project/bin/pdb2cif --dict /project/bin/mmcif_pdbx.dic 1G0D.pdb
```

The error shows:
```
Error loading dictionary /project/bin/mmcif_pdbx.dic
 >> Error reading file /project/bin/mmcif_pdbx.dic
 >> parse error at line 5627: A regular CIF file should not contain a save frame
```

My current working environment is in a docker container. I install cif-tools in another machine and get the exe file and dict file, then pass it into the container. I did it the same way and ran it successfully with mkdssp, but pdb2cif failed. Can you please help me?
Thank you,
Loci

**Comment by mhekkel** [comment]
Did you use mrc to build the cif-tools? If you did, the mmcif_pdbx file is compiled into the executable and you can simply copy such an executable from one machine to another. If you didn't, well, it is a bit more work.

See an explanation here:

https://www.hekkelman.net/libcifpp-doc/resources.html

However, when you built libcifpp and installed it in $HOME/.local, the CIFPP_DATA_DIR is set to $HOME/.local/share/libcifpp. And that path is certainly not on that other machine. To work around this problem, I updated the makefile for libcifpp this week. You can now specify the CIFPP_DATA_DIR and CIFPP_CACHE_DIR variables and make them point to some standard location like /usr/share/libcifpp and /var/cache/libcifpp. Then, when copying the executables, you should also copy the dictionary files to one of those directories on the other machine.

To make configuration easier, you should consider to use ccmake or another cmake gui front-end.

**Comment by locitran** [comment]
I built cif-tools by libcifpp. And libcifpp is installed at $HOME/.local like you said.
First way may be easier for me than modifying the makefile for libcifpp. I will try rebuild cif-tools by using mrc.
Thank you @mhekkel

**Comment by locitran** [comment]
> Did you use mrc to build the cif-tools? If you did, the mmcif_pdbx file is compiled into the executable and you can simply copy such an executable from one machine to another. If you didn't, well, it is a bit more work.

I already installed mrc. Do we have any instruction that use mrc to install cif-tools?

**Comment by mhekkel** [comment]
When you have mrc installed and configure cif-tools, it should **not** give the message:

  Not using resources since mrc was not found

If it does, cmake cannot find mrc and you should add the location where mrc was installed as a CMAKE_PREFIX_PATH to the cmake configure command.

You can also check to see if mrc is being using by looking at the cmake build output, you should see messages like:

[  3%] Generating pdb2cif_rsrc.obj

Which indicates that a resource file is being generated

**Comment by locitran** [comment]
This is the message after I installed the mrc
```bash=
-- Install configuration: ""
-- Installing: /usr/local/bin/mrc
-- Installing: /usr/local/share/mrc/cmake/mrc-config.cmake
-- Installing: /usr/local/share/man/man1/mrc.1
-- Installing: /usr/local/share/doc/mrc//example
-- Installing: /usr/local/share/doc/mrc//example/CMakeLists.txt
-- Installing: /usr/local/share/doc/mrc//example/mrc-user.cpp
-- Installing: /usr/local/share/doc/mrc//example/hello.txt
```

And the mrc directory that contains the config files (src, cmake, build,...) is `/mnt/Tsunami_HHD/newloci/NativeEnsembleWeb_copy/mrc`

I try 2 commands to install cif-tools:
1. `sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-9 CMAKE_PREFIX_PATH=/usr/local/share/mrc`
2. `sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-9 CMAKE_PREFIX_PATH=/mnt/Tsunami_HHD/newloci/NativeEnsembleWeb_copy/mrc`

But they are both rejected 
```
CMake Warning:
  Ignoring extra path from command line:

   "CMAKE_PREFIX_PATH=/mnt/Tsunami_HHD/newloci/NativeEnsembleWeb_copy/mrc"
...

CMake Error at CMakeLists.txt:101 (find_package):
  Could not find a package configuration file provided by "cifpp" (requested
  version 5.1) with any of the following names:

    cifppConfig.cmake
    cifpp-config.cmake

  Add the installation prefix of "cifpp" to CMAKE_PREFIX_PATH or set
  "cifpp_DIR" to a directory containing one of the above files.  If "cifpp"
  provides a separate development package or SDK, be sure it has been
  installed.
```

And required cifpp

**Comment by locitran** [comment]
Hi @mhekkel,

Sorry for bothering you again. But I still don't have a way to install cif-tools using mrc :((
Can you help me please?

**Comment by mhekkel** [comment]
My apologies, I missed this one.

So, you did install mrc. But did you also install libcifpp before building cif-tools? The complaint is that cifppConfig.cmake cannot be found which leads to the conclusion you did not yet install libcifpp. Please try to (re-)build libcifpp and install it in /usr/local as well and then try to build cif-tools.

**Comment by locitran** [comment]
Thank you, @mhekkel 
I will try it.

**Comment by mhekkel** [comment]
seems to be solved?

**Comment by locitran** [comment]
So sorry @mhekkel 
I just tried installing the software this week. And you are correct, it seems to be solved. I can transfer pdb2cif to another machine and run it without mmcif_pdbx file. Thank you for you help.
