### ISSUE TITLE
include/cif++/item.hpp includes cif++/text.hpp that isn't installed

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/cif-tools#7]
[v1.0.12](https://github.com/PDB-REDO/cif-tools/releases/tag/v1.0.12)

**Comment by mhekkel** [comment]
This was an issue in libcifpp 7.0.2 and should have been solved in libcifpp 7.0.3?

**Comment by yurivict** [comment]
libcifpp-7.0.3 doesn't install cif++/text.hpp

**Comment by mhekkel** [comment]
fixed
